name: Deploy website

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'
      - '.forgejo/workflows/deploy-front.yaml'
      - 'webring.nix'
      - 'flake.*'

jobs:
  deploy:
    runs-on: native
    steps:
      - uses: actions/checkout@v3
      - run: |
          nix build -L .#site --option substituters 'https://cache.nixos.org' -o /srv/web/nixwebr.ing
